// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://blzmtescgthdhtimwodv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJsem10ZXNjZ3RoZGh0aW13b2R2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1ODA5MTcsImV4cCI6MjA2MDE1NjkxN30.7KC5QobAlNWBWh2MD0d718gsUSvyalkZjDykgjyNXRE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);